In [3]:
import numpy as np

In [4]:
a = [1,2,3]
b = np.ones((3,3))
print(a)
print(b)

[1, 2, 3]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
print(a@b)
print(np.einsum('i,ij->j',a,b))

[6. 6. 6.]
[6. 6. 6.]
